name: biscuit_dart
description: A starting point for Dart libraries or applications.
version: 0.0.1
publish_to: none

workspace:
  - packages/biscuit_auth

environment:
  sdk: ^3.13.0

dependencies:
  collection: ^1.19.1
  meta: ^1.19.0
  petitparser: ^7.0.2

dev_dependencies:
  analyzer: ^13.3.0
  biscuit_auth:
    path: packages/biscuit_auth
  build: ^4.0.10
  build_runner: ^2.16.0
  code_builder: ^4.12.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  kiri_check: ^1.3.1
  source_gen: ^4.2.4
